# Generated by Django 3.2.6 on 2022-04-26 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id_default', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.IntegerField(default=4, null=True)),
                ('reward', models.IntegerField(default=0)),
                ('point', models.IntegerField(default=0)),
                ('coin', models.IntegerField(default=0)),
                ('phone_number', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app_id', models.IntegerField(default=0)),
                ('code_status', models.IntegerField(default=0, null=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
